### ISSUE TITLE
Email validation issue

### ISSUE THREAD

**Issue by vinodhrajamuralidharan** [DockYard/ember-changeset-validations#120]
- [X] - I've raised a PR regarding the email validation, could you please review and merge?

https://github.com/DockYard/ember-changeset-validations/pull/119

   The issue is, email validation accepts without the domain (like test@gmail).

**Comment by ChavaSobreyra** [comment]
Technically emails without a TLD can still be valid.

``` 
user@com
user@localserver
user@[IPv6:2001:db8::1]
```

All valid emails^^   [source](http://en.wikipedia.org/wiki/Email_address#Examples)

As such the validator should not enforce a TLD.

**Comment by poteto** [comment]
One of the nice things about this addon is that you can create custom validators very easily. The ones that are provided by default are only for convenience, any changes to their behavior should be defined in your own custom validator instead, unless it is a bug.

Would something like this work for you?

```js
// validators/email.js
import buildMessage from 'ember-changeset-validations/utils/validation-errors';

const emailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

export default function validateEmail(opts = {}) {
  return (key, newValue, oldValue, changes, content) => {
    return emailRegex.test(value) || buildMessage(key, 'email', value, options);
  }
}
```

```js
// validations/user.js
import validateEmail from '../validators/email';

export default {
  email: validateEmail(),
};
```

**Comment by poteto** [comment]
One of the nice things about this addon is that you can create custom validators very easily. The ones that are provided by default are only for convenience, any changes to their behavior should be defined in your own custom validator instead, unless it is a bug. Unfortunately, that means I can't accept your PR.

Would something like this work for you?

```js
// validators/email.js
import buildMessage from 'ember-changeset-validations/utils/validation-errors';

const emailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

export default function validateEmail(opts = {}) {
  return (key, newValue, oldValue, changes, content) => {
    return emailRegex.test(value) || buildMessage(key, 'email', value, options);
  }
}
```

```js
// validations/user.js
import validateEmail from '../validators/email';

export default {
  email: validateEmail(),
};
```
