### ISSUE TITLE
Email Validation Update?

### ISSUE THREAD

**Issue by matvacha** [DockYard/ember-changeset-validations#125]
Currently, 

`email: /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/`

This validation allows emails for emails with invalid format, for example: "y@y", this could cause problems for those who use the email validator to check emails but also use a database validator to store authentication credentials. 

I'm not sure if the validation was intended this way. Another validator I have found to work is:

`email: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/`

**Comment by martndemus** [comment]
[Using a regular expression to validate an email address](http://stackoverflow.com/a/201378)

**Comment by poteto** [comment]
This articulates my thoughts on the current email validator we have in this addon: https://hackernoon.com/the-100-correct-way-to-validate-email-addresses-7c4818f24643#.nx0q5vox6

I would recommend looking at this [custom one](https://github.com/DockYard/ember-changeset-validations/issues/120#issuecomment-281254061) if you would like to use your own regex
