### ISSUE TITLE
Ember 1.13.13 support?

### ISSUE THREAD

**Issue by toranb** [DockYard/ember-changeset-validations#127]
After reading through the GH template that pops up when creating an issue ... I'm uncertain if this is a bug/ support like question / or documentation clarification (improvement?). Regardless, I have reproduced it with twiddle and captured a quick/easy to watch animated gif showing the breakdown.

I decided to use this ember addon because it has support for 1.13.13. When I actually implemented this (following the twiddle shown in the README) I discovered an issue worth mentioning.

https://ember-twiddle.com/b70553450d0c7e4e2329e02b7d082e11

With ember 2x and the 2x series template compiler it works as desired. Validations fall off as you type ahead. But with ember 1.13.13 and the older template compiler you are required to add the [ember-get-helper](https://github.com/jmurphyau/ember-get-helper) because without it you get an error.

If you run the twiddle above you will see the following

![validations](https://cloud.githubusercontent.com/assets/147411/24007533/dbe2fcec-0a3c-11e7-8763-1b8cb03297c1.gif)

This makes me think we have 1 of 2 issues

1) the twiddle shows a legit bug in `ember-changeset-validations` (a possible conflict with ember 1.13.13)
2) ember-get-helper is broken with ember 1.13.13 and this implementation of it (as shown in the README)

I wanted to raise awareness mostly so we can update the twiddle/ call out that this implementation may not work for 1.13.13 or find and fix the bug with `ember-changeset-validations` (or `ember-get-helper`)

**Update**

It's worth noting that the actual validations do fall off from the changset itself - it seems to be a visual issue only. I'd guess we either don't notifyPropertyChange correctly or the ember-get-helper isn't picking that notify up as it should

**Update 2**

After I removed the ember-get-helper altogether (by doing the below) I still see this behavior making me think it's between ember 1.13.13/the template compiler? and ember-changeset-validations

```js
{{#if changeset.error.firstName}}
            <ul>
            {{#each changeset.error.firstName.validation as |message|}}
                <li><span>{{message}}</span></li>
            {{/each}}
            </ul>
{{/if}}
```

**Update 3**

Also found this in other related [documentation](https://github.com/DockYard/ember-changeset/blob/master/README.md) and it's broken as well

```js
{{#if changeset.error.firstName}}
  <p>{{changeset.error.firstName.validation}}</p>
{{/if}}
```

**Comment by toranb** [comment]
I found that in the `_validate` method we don't always return a boolean (or string?) as shown in the doc string. In the situation shown below (ember 1.13) we will blindly return an array of 1 item.

![validate](https://cloud.githubusercontent.com/assets/147411/24016721/42753dc6-0a5b-11e7-8223-844dbd5309b3.png)

Then later ... in the `_setProperty` method we do a check to see if the validation variable is a `isSingleValidationArray` and because it's not a boolean (as we expected from the above `_validate` method) we don't correctly notifyPropertyChange (inside the conditional shown below) and instead skip on by. 

![setproperty](https://cloud.githubusercontent.com/assets/147411/24016717/3e6e5a8c-0a5b-11e7-949e-c1ae264b6a2e.png)

Meaning ... we don't alert the UI of this change and the error still shows in ember 1.13. I'll get a PR ready to solve this issue - still unsure what the best "contract" is for that `_validate` method ... would much prefer it return ONLY a boolean (not boolean OR string (and sometimes array?)).

Any push back on fixing that to support just 1 type if possible (still need to test drive that change to learn more/ but on the surface returning 2+ types isn't great for methods that follow as we can see here)

**Comment by toranb** [comment]
I was able to [solve](https://github.com/toranb/ember-changeset/commit/7fb9d1a5af18b7c09716d43f6aad94c0871fb2c3) this by doing a hard set on the `_errors` key when we have a legit form (no validation errors showing up). The part I don't feel great about is that it required me to dump the ember meta key from that object ... 

![screen shot 2017-03-16 at 5 15 47 pm](https://cloud.githubusercontent.com/assets/147411/24020985/a5efea0c-0a6c-11e7-9996-80792a42e06e.png)


On the upside all the tests pass (running in both ember 1.13.13 and 2X). The trick is that I need to use my fork and run the tests for `ember-changeset-validations` to confirm it's not breaking anything. This seems crazy but does indeed solve the problem I found here. When I look deeper into the ember meta key I see a handful of listeners and I'm honestly out of my depth here. Any help is much appreciated :)

**Comment by toranb** [comment]
I've add a PR for both ember-changeset and ember-changeset-validations to solve this. The strange part for me (open to feedback here) is adding production code to one/ and the test case to another :)

If you have time to look it over in the coming month I'd appreciate it (and any feedback about your view on this change /etc)

I did see you support ember 1.13X in the ember try configuration so ... I assume adding support for that version is still on the teams radar. Hope so - this was a nasty bug but the only one I've seen like it thus far :)

Thanks for writing these great addons! Much improved idioms / the future is bright!

**Comment by martndemus** [comment]
I'll let @poteto merge the PR, but I gotta give you a gold 🌟 for the elaborate bug report.
