### ISSUE TITLE
How to use two validation files for same page?

### ISSUE THREAD

**Issue by g8anusha** [DockYard/ember-changeset-validations#154]
Hi,

How to couple two validation files as one? 
For example, I have two different cards in my page, for which I have two separate validation files.
I have them separately because, I can either create and submit (for which both the validation files need to be considered), else if I edit the already present details, I can edit a separate card & save.

Is there any way to achieve the above feature? Kindly guide.

Thanks in advance!

**Comment by poteto** [comment]
Does this answer your question? https://github.com/DockYard/ember-changeset-validations#validation-composition

**Comment by g8anusha** [comment]
Yeah, it did. And, works pretty fine! Thank you :) :100:
