### ISSUE TITLE
ValidatePresence has opposite behavior

### ISSUE THREAD

**Issue by erichonkanen** [DockYard/ember-changeset-validations#157]
sorry I don't have time to set up a dummy link for this but I noticed it twice now...

ember-source: "2.13.3"
ember-changeset: "^1.3.0",
ember-changeset-validations: "^1.2.7",

![image](https://user-images.githubusercontent.com/230757/28750251-b6ff688a-7499-11e7-97bb-2e498f4b4c73.png)

```
export default {
  url: [
    validatePresence(true),
  ],
```

**Comment by ynnoj** [comment]
This was fixed in #140. Bump to `1.2.8`.

**Comment by erichonkanen** [comment]
thanks
