### ISSUE TITLE
Make validator messages object overridable

### ISSUE THREAD

**Issue by poteto** [DockYard/ember-changeset-validations#59]
User should be able to provide their own `messages` POJO that overrides https://github.com/DockYard/ember-changeset-validations/blob/master/addon/validators/messages.js

Will most likely involve an ember-cli hook step

**Comment by Moxide** [comment]
Hello,
Do you think you will simply provide a way to override default messages, or will you go down the `ember-i18n` or `ember-intl` road ? :-)
I just need to translate validation messages in one language, like I did in `ember-cp-validations` by extending the `Messages` object, but with `ember-changeset-validations` I can see no other solution than cloning the repo and customizing.

Oh, and thank you for your great work ! Coming from Elixir/Phoenix, it's such a great pleasure to play in Ember with our beloved changesets ;-)

**Comment by Moxide** [comment]
Works great, thanks !

**Comment by poteto** [comment]
You're welcome! Thanks for using this addon :)
