### ISSUE TITLE
Is there anyway to stop the next validator on the same field if one is invalid?

### ISSUE THREAD

**Issue by jabraok** [DockYard/ember-changeset-validations#97]
Hi,

Thanks for creating a great ember addon.

Here is scenario:
I want to validate email field as a email and unique in DB (the uniqueEmail validator will make a request to server to check unique)
``` 
 email: [
      validateFormat({ type: "email" }),
      uniqueEmail()
    ]
```
I think it would be nice if we check unique email just in case passed validateFormat only (for performance). Is there anyway to do it?

Thanks

**Comment by poteto** [comment]
Hmm, good question. Right now there is no straightforward / clean API to do it. The validator function does receive the `changes` object, but then you'd have to manually validate the email in your uniqueness one, which isn't optimal. Let me think about it a bit more

**Comment by nucleartide** [comment]
I need this too. 😧 Though in my case, I want a successful `validateFormat({ type: 'email' })` to short-circuit and pass the validation.

Maybe a possible API could be something like this?

```js
{
  email: and(
    validateFormat({ type: 'email' }),
    uniqueEmail()
  ),

  anotherEmail: or(
    validateFormat({ type: 'email' }),
    uniqueEmail()
  )
}
```

**Comment by nucleartide** [comment]
FWIW, I implemented the API above and released it as a micro-addon: https://github.com/nucleartide/ember-changeset-hofs

It would be nice to merge this into ember-changeset or ember-changeset-validations or something, but for now I just need it for this app at work. :)

**Comment by poteto** [comment]
This is great, I'd be happy to accept a PR to ECV or if you want to maintain it as a separate addon that would also be ok.

**Comment by jabraok** [comment]
Bravo @nucleartide!
It would be nice if it was a part of ember-changeset-validations addon.

Thanks

**Comment by nucleartide** [comment]
Yes, I will grudgingly add semicolons and make a PR...eventually. :trollface:

**Comment by fknoll** [comment]
@nucleartide 
Will it be possible to compose n-level deep nested and/or logic?

**Comment by nucleartide** [comment]
@fknoll You should be able to, although I'll have to write a test case to make sure.

**Comment by nucleartide** [comment]
@fknoll Here is the test case 😃 : https://github.com/nucleartide/ember-changeset-hofs/blob/046d6e1839220579c6021328d39b5d105e3ce724/tests/unit/integration-test.js

**Comment by fknoll** [comment]
@nucleartide Marvelous :smiley:

**Comment by poteto** [comment]
Great, thanks for the hard work @nucleartide! :)

**Comment by jabraok** [comment]
Hi @poteto,

Is there any release version that solve this issue?

Thanks

**Comment by poteto** [comment]
@jabraok please see https://github.com/nucleartide/ember-changeset-hofs

**Comment by jabraok** [comment]
Thanks @poteto

**Comment by nucleartide** [comment]
i knew this would happen

![screen shot 2017-04-12 at 11 53 48 pm](https://cloud.githubusercontent.com/assets/914228/24989549/663770b8-1fdb-11e7-8b1f-3f56f774eed1.png)

**Comment by greyhwndz** [comment]
@nucleartide are those errors still happening?

**Comment by nucleartide** [comment]
@greyhwndz nope, i fixed them as part of https://github.com/DockYard/ember-changeset-validations/pull/131.
