### ISSUE TITLE
Possible to validate one field based on the value of another field?

### ISSUE THREAD

**Issue by maprules1000** [DockYard/ember-changeset-validations#99]
I have a use case where I want to validate one field based on a value in another field (which, lets say, hasn't been changed).

Right now, using a custom validator, I can only see the validation arguments, field name, old value, new value, and change object. Is it possible to access the object underneath the changeset within a validation function?

**Comment by nucleartide** [comment]
I need this too, this sounds fairly easy to do by just passing in `content` here: https://github.com/DockYard/ember-changeset/blob/master/addon/index.js#L365

Going to fork + PR, if anything I can depend on the fork for this work app.

**Comment by poteto** [comment]
@nucleartide Merged that PR and released

**Comment by maprules1000** [comment]
@poteto then does `ember-changeset-validations` need to be updated to also get the original object to use it in custom validators?

**Comment by nucleartide** [comment]
@maprules1000 i've just been using a forked version of ember-changeset-validations [here](https://github.com/RisingTideGames/ember-changeset-validations) but never bothered to merge it in, will submit a PR

**Comment by maprules1000** [comment]
@nucleartide  🎉 😀 🎉
